export const votesArray = [{
    category: "Entertainment",
    creationDate: "2020-01-23",
    downVotes: 36,
    description: "Vestibulum diam ante, porttitor a odio eget, rhoncus neque. Aenean eu velit libero.",
    image: "kanye.png",
    name: "Kanye West",
    totalVotes: 100,
    upVotes: 64,
  },
  {
    category: "Business",
    creationDate: "2019-12-23",
    downVotes: 64,
    description: "Vestibulum diam ante, porttitor a odio eget, rhoncus neque. Aenean eu velit libero.",
    image: "mark.png",
    name: "Mark Zuckerberg",
    totalVotes: 100,
    upVotes: 36,
  },
  {
    category: "Politics",
    creationDate: "2020-01-23",
    downVotes: 64,
    description: "Vestibulum diam ante, porttitor a odio eget, rhoncus neque. Aenean eu velit libero.",
    image: "cristina.png",
    name: "Cristina Fernandez de Kirchner",
    totalVotes: 100,
    upVotes: 36,
  },
  {
    category: "Entertainment",
    creationDate: "2019-10-23",
    downVotes: 36,
    description: "Vestibulum diam ante, porttitor a odio eget, rhoncus neque. Aenean eu velit libero.",
    image: "melala.png",
    name: "Malala Yousafzai",
    totalVotes: 100,
    upVotes: 64,
  }];